#!/usr/bin/env python3
"""
Generate revised route-proposals.json with 10 routes.
Each route: 5 days (4 driving + 1 camping rest), dog-friendly lodging.
Endpoints: Carmel-by-the-Sea, CA → Parker, CO.
"""

import json

START = {"name": "Carmel-by-the-Sea, CA", "coords": [36.5554, -121.9233]}
END = {"name": "Parker, CO", "coords": [39.5186, -104.7614]}

routes = [
    # ═══════════════════ ROUTE 1: Route 66 Classic ═══════════════════
    {
        "id": 1,
        "name": "The Route 66 Classic",
        "theme": "Follow the Mother Road through the Mojave and across Arizona to Colorado",
        "total_days": 5,
        "total_driving_hours": 22,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Barstow, CA",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [34.8958, -117.0173],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Paso Robles Wine Country", "coords": [35.6265, -120.691], "description": "Central Coast wine town with dog-friendly patio tastings and rolling vineyard views", "type": "town"},
                    {"name": "Tehachapi Loop Railroad", "coords": [35.124, -118.505], "description": "National Historic Landmark where freight trains spiral over themselves — viewable from roadside pulloff", "type": "attraction"},
                    {"name": "Calico Ghost Town", "coords": [34.9453, -116.8678], "description": "Restored 1880s silver mining town with mine tours and boardwalk strolling — dogs welcome on leash", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Barstow", "type": "hotel", "dog_policy": "Dogs welcome free of charge, no size limit, up to 2 pets", "price_range": "$85-120/night"},
                    {"name": "Holiday Inn Express Barstow", "type": "hotel", "dog_policy": "Pets allowed with $25/night fee, up to 50 lbs", "price_range": "$100-140/night"},
                    {"name": "Desert Hills Motor Hotel", "type": "hotel", "dog_policy": "Classic Route 66 motel, dogs welcome with $15 fee", "price_range": "$65-90/night"},
                ],
            },
            {
                "day": 2,
                "start": "Barstow, CA",
                "end": "Flagstaff, AZ",
                "start_coords": [34.8958, -117.0173],
                "end_coords": [35.1983, -111.6513],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Route 66 Seligman", "coords": [35.3269, -112.8756], "description": "Birthplace of Route 66 preservation — vintage diners, neon signs, and the inspiration for Pixar's Cars", "type": "town"},
                    {"name": "Snow Cap Drive-In Seligman", "coords": [35.3278, -112.8767], "description": "Legendary roadside stop with joke-pulling staff and kitschy Route 66 folk art everywhere", "type": "attraction"},
                ],
                "camping": {"name": "Bonito Campground", "type": "campground", "description": "Forest Service campground at the base of Sunset Crater in ponderosa pines — dark skies, volcanic scenery", "coords": [35.3558, -111.5372]},
            },
            {
                "day": 3,
                "start": "Flagstaff, AZ",
                "end": "Flagstaff, AZ",
                "start_coords": [35.1983, -111.6513],
                "end_coords": [35.1983, -111.6513],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Sunset Crater Lava Flow Trail", "coords": [35.3653, -111.5024], "description": "Walk across a 1,000-year-old lava flow with interpretive signs — dogs on leash allowed on paved trail", "type": "national_park"},
                    {"name": "Flagstaff Urban Trail System", "coords": [35.2010, -111.6348], "description": "50+ miles of interconnected trails through ponderosa forest right from town — all dog-friendly", "type": "attraction"},
                    {"name": "Mother Road Brewing Company", "coords": [35.1948, -111.6486], "description": "Dog-friendly patio at Flagstaff's popular Route 66-themed craft brewery", "type": "town"},
                ],
                "camping": {"name": "Bonito Campground", "type": "campground", "description": "Second night at Bonito — explore Sunset Crater, Walnut Canyon, and Flagstaff's trails", "coords": [35.3558, -111.5372]},
            },
            {
                "day": 4,
                "start": "Flagstaff, AZ",
                "end": "Albuquerque, NM",
                "start_coords": [35.1983, -111.6513],
                "end_coords": [35.0844, -106.6504],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Petrified Forest National Park", "coords": [34.9100, -109.7871], "description": "225-million-year-old petrified logs and painted desert badlands — dogs on leash on paved overlooks and roads", "type": "national_park"},
                    {"name": "Standin' on the Corner Park Winslow", "coords": [35.0240, -110.6974], "description": "Eagles 'Take It Easy' tribute with bronze statue and flatbed Ford — quick fun photo stop", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Albuquerque Journal Center", "type": "hotel", "dog_policy": "Dogs welcome free, no size limit", "price_range": "$90-130/night"},
                    {"name": "Hotel Albuquerque at Old Town", "type": "hotel", "dog_policy": "Pets up to 50 lbs, $50 fee per stay, walking distance to Old Town plaza", "price_range": "$140-200/night"},
                    {"name": "Old Town Casita (Airbnb)", "type": "airbnb", "dog_policy": "Fenced yard, dog-friendly, near Bosque trail", "price_range": "$110-160/night"},
                ],
            },
            {
                "day": 5,
                "start": "Albuquerque, NM",
                "end": "Parker, CO",
                "start_coords": [35.0844, -106.6504],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 7,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Santa Fe Plaza", "coords": [35.6870, -105.9378], "description": "Historic 1610 plaza with Native artisan market under the Palace of the Governors portal — dogs welcome outdoors", "type": "town"},
                    {"name": "Raton Pass", "coords": [36.9914, -104.6962], "description": "Historic Santa Fe Trail crossing at the Colorado border — scenic transition from plains to mountains", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 2: Death Valley Express ═══════════════════
    {
        "id": 2,
        "name": "Death Valley Express",
        "theme": "Cross the lowest point in North America and climb through canyon country to Colorado",
        "total_days": 5,
        "total_driving_hours": 23,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Pahrump, NV",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [36.2083, -115.9839],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Trona Pinnacles", "coords": [35.6181, -117.3683], "description": "Over 500 ancient tufa towers rising from a dry lake bed — otherworldly landscape open to explore with dogs", "type": "attraction"},
                    {"name": "Death Valley - Zabriskie Point", "coords": [36.4208, -116.8118], "description": "Golden badlands viewpoint — dogs allowed at the paved overlook area for this iconic desert panorama", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "Best Western Pahrump Station", "type": "hotel", "dog_policy": "Dogs welcome, $20/night pet fee, two pets max", "price_range": "$90-130/night"},
                    {"name": "Holiday Inn Express Pahrump", "type": "hotel", "dog_policy": "Pets allowed with $35 fee per stay", "price_range": "$100-140/night"},
                    {"name": "Desert Oasis Casita (Airbnb)", "type": "airbnb", "dog_policy": "Fenced yard, dog bowls provided, quiet residential area", "price_range": "$85-120/night"},
                ],
            },
            {
                "day": 2,
                "start": "Pahrump, NV",
                "end": "Kanab, UT",
                "start_coords": [36.2083, -115.9839],
                "end_coords": [37.0475, -112.5263],
                "driving_hours": 4.5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Red Rock Canyon", "coords": [36.1357, -115.4279], "description": "13-mile scenic loop through towering red sandstone formations outside Vegas — dogs on leash on trails", "type": "scenic_drive"},
                    {"name": "Coral Pink Sand Dunes State Park", "coords": [37.0357, -112.6514], "description": "Pink-hued sand dunes formed by Navajo Sandstone erosion — dogs welcome, great for sunset romps", "type": "national_park"},
                ],
                "camping": {"name": "Coral Pink Sand Dunes Campground", "type": "campground", "description": "Campground within the state park surrounded by pink sand dunes and red cliffs — stargazing and sunrise dune walks", "coords": [37.0357, -112.6514]},
            },
            {
                "day": 3,
                "start": "Kanab, UT",
                "end": "Kanab, UT",
                "start_coords": [37.0475, -112.5263],
                "end_coords": [37.0475, -112.5263],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Kanab Creek Walk", "coords": [37.0475, -112.5263], "description": "Easy creekside walk through Kanab with red cliff views — dogs love the shallow water crossings", "type": "attraction"},
                    {"name": "Best Friends Animal Sanctuary Visit", "coords": [37.0058, -112.4183], "description": "Nation's largest no-kill animal sanctuary in Angel Canyon — free guided tours, incredibly dog-positive", "type": "attraction"},
                    {"name": "Moqui Cave", "coords": [37.0083, -112.5567], "description": "Roadside natural sandstone cave turned into a quirky museum and trading post — dogs welcome outside", "type": "attraction"},
                ],
                "camping": {"name": "Coral Pink Sand Dunes Campground", "type": "campground", "description": "Second night — spend the rest day exploring Kanab's trails and Best Friends sanctuary", "coords": [37.0357, -112.6514]},
            },
            {
                "day": 4,
                "start": "Kanab, UT",
                "end": "Durango, CO",
                "start_coords": [37.0475, -112.5263],
                "end_coords": [37.2753, -107.8801],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Monument Valley", "coords": [36.9833, -110.1135], "description": "Iconic sandstone buttes rising from the desert floor — self-drive Valley Loop is dog-friendly in your vehicle", "type": "national_park"},
                    {"name": "Four Corners Monument", "coords": [36.9990, -109.0452], "description": "Stand in four states at once — outdoor monument with Navajo vendor stalls, dogs on leash welcome", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Durango", "type": "hotel", "dog_policy": "Dogs welcome free, no size limit, two pets max", "price_range": "$100-150/night"},
                    {"name": "The Rochester Hotel", "type": "hotel", "dog_policy": "Boutique hotel welcoming dogs with beds and bowls, $25/night pet fee", "price_range": "$150-220/night"},
                    {"name": "Animas River Cabin (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly cabin near river trail, fenced area", "price_range": "$130-180/night"},
                ],
            },
            {
                "day": 5,
                "start": "Durango, CO",
                "end": "Parker, CO",
                "start_coords": [37.2753, -107.8801],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Wolf Creek Pass", "coords": [37.4864, -106.7967], "description": "10,857-foot Continental Divide crossing through alpine meadows — pulloffs with mountain panoramas", "type": "scenic_drive"},
                    {"name": "Great Sand Dunes View", "coords": [37.7500, -105.5100], "description": "Distant view of North America's tallest dunes against the Sangre de Cristos from US-160", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 3: Eastern Sierra & Bryce ═══════════════════
    {
        "id": 3,
        "name": "Eastern Sierra & Bryce Canyon",
        "theme": "Chase the Sierra Nevada's dramatic eastern wall into Utah's hoodoo country",
        "total_days": 5,
        "total_driving_hours": 21.5,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Bishop, CA",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [37.3636, -118.3951],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Manzanar National Historic Site", "coords": [36.7284, -118.1543], "description": "WWII Japanese American internment camp — outdoor grounds and walking tour are dog-friendly on leash", "type": "attraction"},
                    {"name": "Alabama Hills", "coords": [36.6065, -118.1118], "description": "Surreal granite boulder landscape at the foot of Mount Whitney — free to explore, dogs welcome everywhere", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Best Western Bishop Holiday Spa Lodge", "type": "hotel", "dog_policy": "Dogs allowed, $20/night pet fee, pool and hot tub area", "price_range": "$100-150/night"},
                    {"name": "The Bishop Creekside Inn", "type": "hotel", "dog_policy": "Pet-friendly rooms available, $15/night fee", "price_range": "$85-120/night"},
                    {"name": "Sierra Meadow Retreat (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly with fenced yard, near Bishop Creek", "price_range": "$110-160/night"},
                ],
            },
            {
                "day": 2,
                "start": "Bishop, CA",
                "end": "Panguitch, UT",
                "start_coords": [37.3636, -118.3951],
                "end_coords": [37.8228, -112.4356],
                "driving_hours": 6,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Tonopah Historic Mining Park", "coords": [38.0678, -117.2303], "description": "Walk among headframes and mining ruins on a hilltop overlooking the Nevada desert — outdoor, dog-friendly", "type": "attraction"},
                    {"name": "Red Canyon", "coords": [37.7456, -112.3306], "description": "Brilliant red hoodoos lining Highway 12 — short trails through the formations, dogs on leash welcome", "type": "scenic_drive"},
                ],
                "camping": {"name": "Red Canyon Campground", "type": "campground", "description": "USFS campground surrounded by vivid red hoodoos along Scenic Byway 12 — gateway to Bryce Canyon", "coords": [37.7456, -112.3306]},
            },
            {
                "day": 3,
                "start": "Panguitch, UT",
                "end": "Panguitch, UT",
                "start_coords": [37.8228, -112.4356],
                "end_coords": [37.8228, -112.4356],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Bryce Canyon Rim Trail", "coords": [37.6283, -112.1671], "description": "Walk along the rim between Sunrise and Sunset Points — dogs on leash allowed on the paved rim path above the hoodoos", "type": "national_park"},
                    {"name": "Bryce Canyon Shared Use Path", "coords": [37.6400, -112.1650], "description": "5-mile paved path from Ruby's Inn to the park — dogs welcome on this connector trail with canyon views", "type": "national_park"},
                    {"name": "Red Canyon Trails", "coords": [37.7456, -112.3306], "description": "Hike the Arches Trail or Thunder Mountain — red rock formations with a fraction of Bryce's crowds, dogs welcome", "type": "attraction"},
                ],
                "camping": {"name": "Red Canyon Campground", "type": "campground", "description": "Second night — full day to explore Bryce and Red Canyon trails", "coords": [37.7456, -112.3306]},
            },
            {
                "day": 4,
                "start": "Panguitch, UT",
                "end": "Steamboat Springs, CO",
                "start_coords": [37.8228, -112.4356],
                "end_coords": [40.4850, -106.8317],
                "driving_hours": 7,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Capitol Reef Scenic Drive", "coords": [38.2916, -111.2628], "description": "Drive through the Waterpocket Fold along the Fremont River — dogs allowed in vehicle and at pulloffs", "type": "national_park"},
                    {"name": "San Rafael Swell Viewpoint", "coords": [38.9500, -110.6500], "description": "Vast geologic uplift visible from I-70 — The Wedge overlook offers a mini Grand Canyon vista", "type": "scenic_drive"},
                ],
                "lodging": [
                    {"name": "Holiday Inn Steamboat Springs", "type": "hotel", "dog_policy": "Dogs welcome with $35/night fee, near downtown and trails", "price_range": "$120-180/night"},
                    {"name": "Rabbit Ears Motel", "type": "motel", "dog_policy": "Classic mountain motel, dogs welcome free, no size limit", "price_range": "$80-130/night"},
                    {"name": "Mountain View Condo (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, private patio, near Yampa River Core Trail", "price_range": "$130-200/night"},
                ],
            },
            {
                "day": 5,
                "start": "Steamboat Springs, CO",
                "end": "Parker, CO",
                "start_coords": [40.4850, -106.8317],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 3.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Rabbit Ears Pass", "coords": [40.3844, -106.6614], "description": "9,426-foot pass through dense spruce-fir forest — the distinctive twin rock formations are visible from the road", "type": "scenic_drive"},
                    {"name": "Berthoud Pass", "coords": [39.7981, -105.7775], "description": "11,315-foot Continental Divide crossing on US-40 with alpine tundra views — a stunning descent into the Front Range", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 4: Grand Canyon Road ═══════════════════
    {
        "id": 4,
        "name": "The Grand Canyon Road",
        "theme": "From the Pacific to the planet's greatest gorge, then across Navajo country to Colorado",
        "total_days": 5,
        "total_driving_hours": 22,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Kingman, AZ",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [35.1894, -114.0530],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Mojave National Preserve", "coords": [35.1414, -115.5109], "description": "Kelso Depot visitor center and vast desert scenery — dogs on leash at pulloffs and picnic areas", "type": "national_park"},
                    {"name": "Route 66 Museum Kingman", "coords": [35.19, -114.056], "description": "Housed in the 1907 Powerhouse, tracing Route 66 decade by decade — outdoor areas dog-friendly", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Best Western Plus King's Inn & Suites", "type": "hotel", "dog_policy": "Dogs welcome, $20/night pet fee, grassy walking area", "price_range": "$80-120/night"},
                    {"name": "La Quinta Inn & Suites Kingman", "type": "hotel", "dog_policy": "Dogs welcome free, no size limit", "price_range": "$75-110/night"},
                    {"name": "Route 66 Retreat (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly casita, fenced backyard, near Hualapai Mountain Park", "price_range": "$85-130/night"},
                ],
            },
            {
                "day": 2,
                "start": "Kingman, AZ",
                "end": "Grand Canyon Village, AZ",
                "start_coords": [35.1894, -114.0530],
                "end_coords": [36.0544, -112.1401],
                "driving_hours": 3.5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Route 66 Historic Downtown Williams", "coords": [35.2494, -112.1871], "description": "Last town bypassed by I-40 — original neon signs, diners, and the Grand Canyon Railway depot", "type": "town"},
                    {"name": "Mather Point", "coords": [36.0600, -112.1077], "description": "First jaw-dropping Grand Canyon viewpoint — paved overlook, dogs on leash at the rim", "type": "national_park"},
                ],
                "camping": {"name": "Mather Campground", "type": "campground", "description": "Primary South Rim campground in ponderosa forest — walking distance to Rim Trail and village amenities", "coords": [36.0492, -112.1180]},
            },
            {
                "day": 3,
                "start": "Grand Canyon Village, AZ",
                "end": "Grand Canyon Village, AZ",
                "start_coords": [36.0544, -112.1401],
                "end_coords": [36.0544, -112.1401],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Grand Canyon Rim Trail", "coords": [36.0569, -112.1432], "description": "13-mile paved rim path — dogs on leash welcome along the entire trail above the canyon", "type": "national_park"},
                    {"name": "Shoshone Point", "coords": [36.0494, -112.0876], "description": "Hidden viewpoint via a quiet 1-mile forest walk — peaceful, uncrowded, dogs on leash", "type": "national_park"},
                    {"name": "Greenway Trail", "coords": [36.0520, -112.1300], "description": "Paved multi-use path connecting visitor center to Hermit's Rest — separate from the rim, less crowded for dog walks", "type": "attraction"},
                ],
                "camping": {"name": "Mather Campground", "type": "campground", "description": "Second night — full day to walk the rim, catch sunset at Hopi Point, and enjoy the canyon at your pace", "coords": [36.0492, -112.1180]},
            },
            {
                "day": 4,
                "start": "Grand Canyon Village, AZ",
                "end": "Pagosa Springs, CO",
                "start_coords": [36.0544, -112.1401],
                "end_coords": [37.2694, -107.0098],
                "driving_hours": 6,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Cameron Trading Post", "coords": [35.8598, -111.4224], "description": "Historic 1916 Navajo trading post with galleries and restaurant — great Navajo tacos, outdoor areas dog-friendly", "type": "attraction"},
                    {"name": "Navajo Bridge", "coords": [36.8114, -111.6318], "description": "Pedestrian bridge 470 feet above the Colorado River — look for condors, dogs on leash on the walkway", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Fireside Inn Pagosa Springs", "type": "hotel", "dog_policy": "Dogs welcome with $15/night fee, grassy areas for walking", "price_range": "$90-140/night"},
                    {"name": "Best Western Plus Pagosa Springs", "type": "hotel", "dog_policy": "Pets allowed, $20/night fee, near hot springs", "price_range": "$110-160/night"},
                    {"name": "San Juan River Retreat (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly cabin with yard, near river trail", "price_range": "$120-170/night"},
                ],
            },
            {
                "day": 5,
                "start": "Pagosa Springs, CO",
                "end": "Parker, CO",
                "start_coords": [37.2694, -107.0098],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 6,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Wolf Creek Pass", "coords": [37.4864, -106.7967], "description": "10,857-foot Continental Divide crossing — alpine meadows and mountain views from pulloffs", "type": "scenic_drive"},
                    {"name": "Spanish Peaks Vista", "coords": [37.3755, -104.9878], "description": "Twin volcanic peaks visible from I-25 corridor — the Great Dikes radiate like stone walls", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 5: Zion & Canyonlands ═══════════════════
    {
        "id": 5,
        "name": "Zion to Canyonlands",
        "theme": "Two of Utah's crown jewels connected by the dramatic landscapes of canyon country",
        "total_days": 5,
        "total_driving_hours": 20.5,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Las Vegas, NV",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [36.1699, -115.1398],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Mojave National Preserve - Cima Road", "coords": [35.2872, -115.5380], "description": "Drive through the world's densest Joshua tree forest along Cima Road — pulloffs for photos with dogs", "type": "scenic_drive"},
                    {"name": "Seven Magic Mountains", "coords": [35.8625, -115.2667], "description": "Colorful stacked boulder art installation in the desert south of Vegas — outdoor, dogs welcome", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Las Vegas Summerlin", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit, near Red Rock Canyon", "price_range": "$80-130/night"},
                    {"name": "Red Rock Casino Resort", "type": "hotel", "dog_policy": "Dogs under 50 lbs, $100 non-refundable fee, luxury pet amenities", "price_range": "$150-250/night"},
                    {"name": "Desert Modern Casita (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly home near Summerlin trail system, fenced yard", "price_range": "$100-160/night"},
                ],
            },
            {
                "day": 2,
                "start": "Las Vegas, NV",
                "end": "Springdale, UT",
                "start_coords": [36.1699, -115.1398],
                "end_coords": [37.1890, -112.9988],
                "driving_hours": 3,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Valley of Fire State Park", "coords": [36.4419, -114.5134], "description": "Brilliant red Aztec sandstone formations — dogs on leash on trails, spectacular sunrise or sunset drive", "type": "national_park"},
                    {"name": "Zion Canyon Scenic Drive", "coords": [37.2500, -112.9500], "description": "Towering 2,000-foot canyon walls along the Virgin River — dogs in vehicles on the scenic drive", "type": "scenic_drive"},
                ],
                "camping": {"name": "Watchman Campground", "type": "campground", "description": "Zion's premier campground along the Virgin River — sites shaded by cottonwoods with canyon wall views", "coords": [37.1965, -112.9869]},
            },
            {
                "day": 3,
                "start": "Springdale, UT",
                "end": "Springdale, UT",
                "start_coords": [37.1890, -112.9988],
                "end_coords": [37.1890, -112.9988],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Pa'rus Trail", "coords": [37.2018, -112.9861], "description": "3.5-mile paved riverside trail — one of only two Zion trails allowing dogs, with stunning canyon views", "type": "national_park"},
                    {"name": "Springdale Town Walk", "coords": [37.1890, -112.9988], "description": "Walkable gateway town with galleries, restaurants, and outfitters — very dog-friendly atmosphere", "type": "town"},
                    {"name": "Grafton Ghost Town", "coords": [37.1657, -113.0731], "description": "Abandoned 1859 Mormon settlement with photogenic buildings against Zion cliffs — open and dog-friendly", "type": "attraction"},
                ],
                "camping": {"name": "Watchman Campground", "type": "campground", "description": "Second night — walk the Pa'rus Trail, explore Springdale, relax by the Virgin River", "coords": [37.1965, -112.9869]},
            },
            {
                "day": 4,
                "start": "Springdale, UT",
                "end": "Moab, UT",
                "start_coords": [37.1890, -112.9988],
                "end_coords": [38.5733, -109.5498],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Capitol Reef Scenic Drive", "coords": [38.2916, -111.2628], "description": "Free-entry scenic drive along the Waterpocket Fold — dogs at pulloffs and picnic areas", "type": "national_park"},
                    {"name": "Goblin Valley State Park", "coords": [38.5670, -110.7077], "description": "Thousands of mushroom-shaped hoodoos — dogs on leash, and you can wander freely among the 'goblins'", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Moab", "type": "hotel", "dog_policy": "Dogs welcome free, no size limit", "price_range": "$110-170/night"},
                    {"name": "Red Cliffs Lodge", "type": "hotel", "dog_policy": "Dog-friendly rooms with $25/night fee, Colorado River frontage, on-site winery", "price_range": "$180-280/night"},
                    {"name": "Moab Canyon Casita (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, private patio, near trailheads", "price_range": "$120-180/night"},
                ],
            },
            {
                "day": 5,
                "start": "Moab, UT",
                "end": "Parker, CO",
                "start_coords": [38.5733, -109.5498],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Colorado River Scenic Byway", "coords": [39.0700, -108.7300], "description": "I-70 follows the Colorado River through red-walled canyons — scenic rest areas with river access for dogs", "type": "scenic_drive"},
                    {"name": "Glenwood Canyon Rest Stop", "coords": [39.5647, -107.2295], "description": "Stop at the Grizzly Creek rest area for a short walk along the Colorado River in the heart of the canyon", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 6: The Loneliest Road ═══════════════════
    {
        "id": 6,
        "name": "The Loneliest Road",
        "theme": "Cross the emptiest stretch of highway in America through Nevada's basin and range",
        "total_days": 5,
        "total_driving_hours": 20.5,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Reno, NV",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [39.5296, -119.8138],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Sacramento Old Town", "coords": [38.5832, -121.5049], "description": "Gold Rush-era waterfront district with boardwalks and the California Railroad Museum — dogs welcome on streets", "type": "town"},
                    {"name": "Donner Memorial State Park", "coords": [39.2389, -120.2318], "description": "Alpine park on Donner Lake with hiking trails and the Emigrant Trail Museum — dogs on leash on trails", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Reno", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit", "price_range": "$80-120/night"},
                    {"name": "Whitney Peak Hotel", "type": "hotel", "dog_policy": "Boutique hotel, dogs up to 50 lbs welcome with $50 fee, downtown location", "price_range": "$120-180/night"},
                    {"name": "Midtown Reno Bungalow (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, fenced yard, walkable to Riverwalk", "price_range": "$90-140/night"},
                ],
            },
            {
                "day": 2,
                "start": "Reno, NV",
                "end": "Ely, NV",
                "start_coords": [39.5296, -119.8138],
                "end_coords": [39.2533, -114.8764],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Sand Mountain Recreation Area", "coords": [39.2846, -118.1311], "description": "600-foot singing sand dune in the Nevada desert — dogs welcome, bring water and enjoy the vast silence", "type": "attraction"},
                    {"name": "Ward Charcoal Ovens", "coords": [39.0769, -115.0422], "description": "Six perfectly preserved beehive-shaped stone kilns from the 1870s silver mining era — dogs on leash welcome", "type": "attraction"},
                ],
                "camping": {"name": "Cave Lake State Park", "type": "campground", "description": "Mountain lake campground at 7,300 feet in the Schell Creek Range near Ely — trout fishing, kayaking, pines", "coords": [39.1672, -114.8164]},
            },
            {
                "day": 3,
                "start": "Ely, NV",
                "end": "Ely, NV",
                "start_coords": [39.2533, -114.8764],
                "end_coords": [39.2533, -114.8764],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Cave Lake Shoreline Trail", "coords": [39.1672, -114.8164], "description": "Walk the lakeshore through juniper and pine forest — calm water for dogs to swim, mountain views", "type": "attraction"},
                    {"name": "Nevada Northern Railway", "coords": [39.2461, -114.8639], "description": "Ride behind a century-old steam locomotive — dogs allowed on select excursion cars, check schedules", "type": "attraction"},
                    {"name": "Ely Renaissance Village", "coords": [39.2500, -114.8700], "description": "Walk through restored historic buildings representing Ely's diverse immigrant mining communities", "type": "town"},
                ],
                "camping": {"name": "Cave Lake State Park", "type": "campground", "description": "Second night — swim, fish, hike the lakeshore, and ride the historic railroad", "coords": [39.1672, -114.8164]},
            },
            {
                "day": 4,
                "start": "Ely, NV",
                "end": "Grand Junction, CO",
                "start_coords": [39.2533, -114.8764],
                "end_coords": [39.0639, -108.5506],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Great Basin Highway Overlook", "coords": [39.0050, -113.8500], "description": "Sweeping views across the Great Basin's mountain ranges and valleys from US-93 pulloffs", "type": "scenic_drive"},
                    {"name": "San Rafael Swell - I-70", "coords": [38.9500, -110.6500], "description": "Drive through the spectacular San Rafael Reef along I-70 — dramatic geology visible right from the highway", "type": "scenic_drive"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Grand Junction", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit", "price_range": "$90-130/night"},
                    {"name": "SpringHill Suites Grand Junction", "type": "hotel", "dog_policy": "Pets allowed with $75 non-refundable fee, spacious suites", "price_range": "$120-170/night"},
                    {"name": "Mesa County Ranch House (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly property with fenced yard, near Colorado National Monument", "price_range": "$100-150/night"},
                ],
            },
            {
                "day": 5,
                "start": "Grand Junction, CO",
                "end": "Parker, CO",
                "start_coords": [39.0639, -108.5506],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 4.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Glenwood Canyon", "coords": [39.5647, -107.2295], "description": "12-mile I-70 canyon with 1,300-foot walls — stop at Grizzly Creek rest area for riverside walks with dogs", "type": "scenic_drive"},
                    {"name": "Eisenhower Tunnel Vista", "coords": [39.6790, -105.9107], "description": "Highest point on the US Interstate system at 11,158 feet — pull off for alpine tundra views", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 7: Sedona Spirit ═══════════════════
    {
        "id": 7,
        "name": "Sedona Spirit",
        "theme": "Red rock vortex country and the enchantment of the Southwest",
        "total_days": 5,
        "total_driving_hours": 23,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Barstow, CA",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [34.8958, -117.0173],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Paso Robles Wine Country", "coords": [35.6265, -120.691], "description": "Central Coast wine town with dog-friendly patio tastings — try Tablas Creek or Eberle", "type": "town"},
                    {"name": "Tehachapi Wind Farm", "coords": [35.078, -118.371], "description": "Thousands of wind turbines stretching across the mountain pass — surreal industrial-meets-nature views from the highway", "type": "scenic_drive"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Barstow", "type": "hotel", "dog_policy": "Dogs welcome free, no size limit", "price_range": "$85-120/night"},
                    {"name": "Idle Spurs Steakhouse & Lodging", "type": "hotel", "dog_policy": "Historic Route 66 property, dogs welcome with $15 fee", "price_range": "$70-100/night"},
                    {"name": "Desert View Cottage (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, fully fenced yard, quiet street", "price_range": "$80-120/night"},
                ],
            },
            {
                "day": 2,
                "start": "Barstow, CA",
                "end": "Sedona, AZ",
                "start_coords": [34.8958, -117.0173],
                "end_coords": [34.8697, -111.7610],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Hualapai Mountain Park", "coords": [35.08, -113.897], "description": "Pine-forested mountain park at 8,400 feet above Kingman — dog-friendly trails and cooler mountain air", "type": "national_park"},
                    {"name": "Oak Creek Canyon Scenic Drive", "coords": [35.0200, -111.7300], "description": "14-mile descent through red and white sandstone canyon walls — Arizona's mini Grand Canyon", "type": "scenic_drive"},
                ],
                "camping": {"name": "Cave Springs Campground", "type": "campground", "description": "Shaded creekside campground in Oak Creek Canyon surrounded by red rock walls — dogs on leash, creek access", "coords": [34.9667, -111.7500]},
            },
            {
                "day": 3,
                "start": "Sedona, AZ",
                "end": "Sedona, AZ",
                "start_coords": [34.8697, -111.7610],
                "end_coords": [34.8697, -111.7610],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Bell Rock Pathway", "coords": [34.8072, -111.7687], "description": "3.6-mile loop circling Sedona's iconic bell-shaped butte — dogs on leash, vortex energy site", "type": "attraction"},
                    {"name": "Tlaquepaque Arts Village", "coords": [34.8597, -111.7588], "description": "Spanish colonial arts village with fountains and galleries — dog-friendly courtyards and outdoor dining", "type": "town"},
                    {"name": "Airport Mesa Overlook", "coords": [34.8586, -111.7790], "description": "360-degree panoramic views of all Sedona's red rock formations — famous sunset spot, dogs welcome", "type": "attraction"},
                ],
                "camping": {"name": "Cave Springs Campground", "type": "campground", "description": "Second night — full day to hike Bell Rock, explore Tlaquepaque, and catch sunset at Airport Mesa", "coords": [34.9667, -111.7500]},
            },
            {
                "day": 4,
                "start": "Sedona, AZ",
                "end": "Santa Fe, NM",
                "start_coords": [34.8697, -111.7610],
                "end_coords": [35.6870, -105.9378],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Meteor Crater", "coords": [35.0275, -111.0223], "description": "Best-preserved meteorite impact crater on Earth — outdoor viewing platform, dogs allowed on observation deck", "type": "attraction"},
                    {"name": "Albuquerque Old Town", "coords": [35.0966, -106.6691], "description": "Historic 1706 Spanish plaza with adobe shops and restaurants — walk the outdoor plazas with your dog", "type": "town"},
                ],
                "lodging": [
                    {"name": "La Fonda on the Plaza", "type": "hotel", "dog_policy": "Historic hotel on Santa Fe Plaza, pets welcome with $100 fee, pet bed provided", "price_range": "$200-350/night"},
                    {"name": "La Quinta Inn & Suites Santa Fe", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit", "price_range": "$90-140/night"},
                    {"name": "Adobe Compound (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly adobe home with courtyard, walking distance to Canyon Road galleries", "price_range": "$130-200/night"},
                ],
            },
            {
                "day": 5,
                "start": "Santa Fe, NM",
                "end": "Parker, CO",
                "start_coords": [35.6870, -105.9378],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 6,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Santa Fe Plaza Morning Walk", "coords": [35.6870, -105.9378], "description": "Walk the oldest public plaza in the US before hitting the road — artisan vendors under the Palace portal", "type": "town"},
                    {"name": "Raton Pass", "coords": [36.9914, -104.6962], "description": "Scenic mountain pass at the CO/NM border — historic Santa Fe Trail gateway with rest area overlook", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 8: Lake Powell & Navajo Country ═══════════════════
    {
        "id": 8,
        "name": "Lake Powell & Navajo Country",
        "theme": "Desert waterways, ancient cultures, and the red rock heart of the Colorado Plateau",
        "total_days": 5,
        "total_driving_hours": 23,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Las Vegas, NV",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [36.1699, -115.1398],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Morro Rock Vista", "coords": [35.3713, -120.8659], "description": "576-foot volcanic plug at the harbor mouth — stop for photos and a walk along the Embarcadero with your dog", "type": "attraction"},
                    {"name": "Mojave National Preserve", "coords": [35.1414, -115.5109], "description": "Kelso Dunes and vast desert scenery — dogs at pulloffs and parking areas along the preserve roads", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Las Vegas Airport South", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit", "price_range": "$75-120/night"},
                    {"name": "Element Las Vegas Summerlin", "type": "hotel", "dog_policy": "Extended-stay hotel, dogs welcome with $100 non-refundable fee, near trails", "price_range": "$110-160/night"},
                    {"name": "Henderson Desert Home (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, pool, fenced backyard", "price_range": "$100-150/night"},
                ],
            },
            {
                "day": 2,
                "start": "Las Vegas, NV",
                "end": "Page, AZ",
                "start_coords": [36.1699, -115.1398],
                "end_coords": [36.9147, -111.4558],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Vermilion Cliffs", "coords": [36.8100, -111.7430], "description": "Massive 3,000-foot escarpment of red and orange sandstone — look for California condors soaring the cliffs", "type": "scenic_drive"},
                    {"name": "Horseshoe Bend", "coords": [36.8791, -111.5104], "description": "Colorado River's famous 270-degree meander seen from 1,000 feet above — 1.5-mile walk, dogs on leash", "type": "attraction"},
                ],
                "camping": {"name": "Wahweap Campground", "type": "campground", "description": "Campground on the shores of Lake Powell near Page — sunset views over the desert lake and red mesa country", "coords": [36.9967, -111.4856]},
            },
            {
                "day": 3,
                "start": "Page, AZ",
                "end": "Page, AZ",
                "start_coords": [36.9147, -111.4558],
                "end_coords": [36.9147, -111.4558],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Wahweap Overlook Trail", "coords": [36.9967, -111.4856], "description": "Walk the rim above Lake Powell for panoramic views of the turquoise water and red rock canyons", "type": "attraction"},
                    {"name": "Glen Canyon Dam Overlook", "coords": [36.9372, -111.4836], "description": "Views of the 710-foot dam and the canyon below — outdoor walkway, dogs on leash", "type": "attraction"},
                    {"name": "Chains Trail Area", "coords": [36.9300, -111.4700], "description": "Short hikes in the sandstone formations near Page — slickrock walking with canyon views, dogs welcome", "type": "attraction"},
                ],
                "camping": {"name": "Wahweap Campground", "type": "campground", "description": "Second night — explore Lake Powell shoreline, Glen Canyon Dam, and the surrounding desert at your own pace", "coords": [36.9967, -111.4856]},
            },
            {
                "day": 4,
                "start": "Page, AZ",
                "end": "Cortez, CO",
                "start_coords": [36.9147, -111.4558],
                "end_coords": [37.3489, -108.5859],
                "driving_hours": 5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Monument Valley", "coords": [36.9833, -110.1135], "description": "Iconic sandstone buttes — self-drive loop is dog-friendly in your car, amazing valley floor views", "type": "national_park"},
                    {"name": "Four Corners Monument", "coords": [36.9990, -109.0452], "description": "Stand in four states simultaneously — outdoor monument, dogs on leash, Navajo vendor stalls", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Best Western Turquoise Inn & Suites Cortez", "type": "hotel", "dog_policy": "Dogs welcome, $20/night pet fee, near Mesa Verde", "price_range": "$90-140/night"},
                    {"name": "Holiday Inn Express Cortez", "type": "hotel", "dog_policy": "Pets allowed with $25/night fee, pool", "price_range": "$100-150/night"},
                    {"name": "Mesa Verde View Cabin (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly cabin with porch, mountain views", "price_range": "$110-160/night"},
                ],
            },
            {
                "day": 5,
                "start": "Cortez, CO",
                "end": "Parker, CO",
                "start_coords": [37.3489, -108.5859],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 6.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Animas River Trail Durango", "coords": [37.2753, -107.8801], "description": "7-mile paved riverwalk through downtown Durango — dogs on leash, great for a leg-stretching break", "type": "attraction"},
                    {"name": "Wolf Creek Pass", "coords": [37.4864, -106.7967], "description": "Alpine pass at 10,857 feet crossing the Continental Divide — mountain meadows and panoramic pulloffs", "type": "scenic_drive"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 9: Capitol Reef Crossing ═══════════════════
    {
        "id": 9,
        "name": "Capitol Reef Crossing",
        "theme": "Utah's most underrated national park anchoring a journey through the state's canyon heartland",
        "total_days": 5,
        "total_driving_hours": 20.5,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Lone Pine, CA",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [36.6060, -118.0625],
                "driving_hours": 4.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Manzanar National Historic Site", "coords": [36.7284, -118.1543], "description": "WWII internment camp memorial — outdoor grounds with walking paths, dogs on leash on the grounds", "type": "attraction"},
                    {"name": "Alabama Hills", "coords": [36.6065, -118.1118], "description": "Surreal granite boulders at Mount Whitney's base — free to explore, dogs welcome, incredible sunset spot", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Best Western Plus Frontier Motel Lone Pine", "type": "hotel", "dog_policy": "Dogs welcome with $20/night fee, mountain views from rooms", "price_range": "$100-150/night"},
                    {"name": "Dow Villa Motel", "type": "hotel", "dog_policy": "Historic motel where movie stars stayed, dogs welcome with $15 fee", "price_range": "$80-120/night"},
                    {"name": "Sierra View Cabin (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, Mount Whitney views, near Alabama Hills", "price_range": "$110-160/night"},
                ],
            },
            {
                "day": 2,
                "start": "Lone Pine, CA",
                "end": "Torrey, UT",
                "start_coords": [36.6060, -118.0625],
                "end_coords": [38.3000, -111.4200],
                "driving_hours": 7,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Mono Lake South Tufa", "coords": [37.9403, -119.0277], "description": "Otherworldly tufa towers rising from ancient alkaline lake — short boardwalk, dogs on leash at the trailhead area", "type": "attraction"},
                    {"name": "Capitol Reef Scenic Drive", "coords": [38.2916, -111.2628], "description": "Enter the Waterpocket Fold along the Fremont River — scenic drive with pulloffs, dogs at overlooks", "type": "national_park"},
                ],
                "camping": {"name": "Fruita Campground", "type": "campground", "description": "Capitol Reef's main campground in a pioneer-era fruit orchard along the Fremont River — pick fruit in season, shaded sites", "coords": [38.2825, -111.2478]},
            },
            {
                "day": 3,
                "start": "Torrey, UT",
                "end": "Torrey, UT",
                "start_coords": [38.3000, -111.4200],
                "end_coords": [38.3000, -111.4200],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Fremont River Trail", "coords": [38.2850, -111.2500], "description": "1.5-mile trail along the Fremont River through the orchard — flat, shaded, dogs on leash welcome", "type": "national_park"},
                    {"name": "Panorama Point", "coords": [38.2950, -111.2700], "description": "Overlook with 180-degree views of the Waterpocket Fold, Henry Mountains, and Boulder Mountain", "type": "national_park"},
                    {"name": "Capitol Reef Petroglyphs", "coords": [38.2890, -111.2540], "description": "Fremont culture rock art panels visible from the roadside boardwalk — dogs welcome at the viewing area", "type": "attraction"},
                ],
                "camping": {"name": "Fruita Campground", "type": "campground", "description": "Second night — hike the river trail, view petroglyphs, pick fruit from the historic orchards", "coords": [38.2825, -111.2478]},
            },
            {
                "day": 4,
                "start": "Torrey, UT",
                "end": "Grand Junction, CO",
                "start_coords": [38.3000, -111.4200],
                "end_coords": [39.0639, -108.5506],
                "driving_hours": 4.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "San Rafael Swell - I-70", "coords": [38.9500, -110.6500], "description": "Drive through the San Rafael Reef — I-70 cuts through 1,000-foot sandstone walls in a dramatic geological corridor", "type": "scenic_drive"},
                    {"name": "Colorado National Monument", "coords": [39.1000, -108.6900], "description": "Red rock canyons and monoliths along Rim Rock Drive near Grand Junction — dogs at overlooks on leash", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "La Quinta Inn & Suites Grand Junction", "type": "hotel", "dog_policy": "Dogs welcome free, no weight limit", "price_range": "$90-130/night"},
                    {"name": "Wine Country Inn Palisade", "type": "hotel", "dog_policy": "Pet-friendly rooms, $25 fee, near Palisade wine tasting rooms", "price_range": "$130-190/night"},
                    {"name": "Orchard Mesa Homestead (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly, private yard, mountain views", "price_range": "$100-150/night"},
                ],
            },
            {
                "day": 5,
                "start": "Grand Junction, CO",
                "end": "Parker, CO",
                "start_coords": [39.0639, -108.5506],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 4.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Glenwood Canyon", "coords": [39.5647, -107.2295], "description": "12-mile canyon along I-70 — Grizzly Creek rest area has riverside walks perfect for dogs", "type": "scenic_drive"},
                    {"name": "Vail Village", "coords": [39.6403, -106.3742], "description": "Pedestrian alpine village with dog-friendly patios, summer gondola rides, and mountain views", "type": "town"},
                ],
            },
        ],
    },

    # ═══════════════════ ROUTE 10: Mono Lake & Colorado Rockies ═══════════════════
    {
        "id": 10,
        "name": "Mono Lake & Colorado Rockies",
        "theme": "Ancient volcanic lakes, Great Basin emptiness, and a grand entrance into the Rocky Mountains",
        "total_days": 5,
        "total_driving_hours": 22.0,
        "days": [
            {
                "day": 1,
                "start": "Carmel-by-the-Sea, CA",
                "end": "Mammoth Lakes, CA",
                "start_coords": [36.5554, -121.9233],
                "end_coords": [37.6485, -118.9721],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Ancient Bristlecone Pine Forest", "coords": [37.3857, -118.1706], "description": "Oldest living trees on Earth (4,800+ years) at 10,000 feet — dogs on leash on the Schulman Grove trail", "type": "national_park"},
                    {"name": "Convict Lake", "coords": [37.5889, -118.8546], "description": "Glacial lake surrounded by colorful peaks — easy 2.5-mile dog-friendly loop trail around the lake", "type": "attraction"},
                ],
                "lodging": [
                    {"name": "Juniper Springs Resort", "type": "hotel", "dog_policy": "Dog-friendly condos, $25/night pet fee, mountain village setting", "price_range": "$120-200/night"},
                    {"name": "Sierra Nevada Resort", "type": "hotel", "dog_policy": "Pets welcome with $25/night fee, near bike paths and trails", "price_range": "$100-160/night"},
                    {"name": "Mountain Chalet (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly cabin in the pines, near Lakes Basin", "price_range": "$130-190/night"},
                ],
            },
            {
                "day": 2,
                "start": "Mammoth Lakes, CA",
                "end": "Ely, NV",
                "start_coords": [37.6485, -118.9721],
                "end_coords": [39.2533, -114.8764],
                "driving_hours": 5.5,
                "is_rest_day": False,
                "is_camping": True,
                "highlights": [
                    {"name": "Mono Lake South Tufa", "coords": [37.9403, -119.0277], "description": "Tufa towers rising from alkaline water — short walk to formations, dogs on leash at the trailhead area", "type": "attraction"},
                    {"name": "Tonopah Stargazing Park", "coords": [38.0678, -117.2303], "description": "One of the darkest skies in the lower 48 — evening arrival means you can stargaze on the way through", "type": "attraction"},
                ],
                "camping": {"name": "Cave Lake State Park", "type": "campground", "description": "Mountain lake camp at 7,300 feet near Ely — pine forest, trout fishing, kayaking in clear mountain water", "coords": [39.1672, -114.8164]},
            },
            {
                "day": 3,
                "start": "Ely, NV",
                "end": "Ely, NV",
                "start_coords": [39.2533, -114.8764],
                "end_coords": [39.2533, -114.8764],
                "driving_hours": 0,
                "is_rest_day": True,
                "is_camping": True,
                "highlights": [
                    {"name": "Cave Lake Trails", "coords": [39.1672, -114.8164], "description": "Hike the lakeshore and surrounding hills through juniper forest — dogs welcome, great swimming spots", "type": "attraction"},
                    {"name": "Ward Charcoal Ovens", "coords": [39.0769, -115.0422], "description": "Six photogenic 1870s stone kilns — short drive from camp, outdoor site, dogs welcome on leash", "type": "attraction"},
                    {"name": "Ely Main Street Walk", "coords": [39.2500, -114.8700], "description": "Stroll the historic mining town's main strip — murals, small shops, and the Hotel Nevada", "type": "town"},
                ],
                "camping": {"name": "Cave Lake State Park", "type": "campground", "description": "Second night — swim, fish, hike, and visit the charcoal ovens at your own pace", "coords": [39.1672, -114.8164]},
            },
            {
                "day": 4,
                "start": "Ely, NV",
                "end": "Gunnison, CO",
                "start_coords": [39.2533, -114.8764],
                "end_coords": [38.5458, -106.9253],
                "driving_hours": 7,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Great Basin Highway Views", "coords": [39.0050, -113.8500], "description": "Basin and range valleys stretching to the horizon — classic Nevada open-road driving with mountain ridges", "type": "scenic_drive"},
                    {"name": "Colorado National Monument", "coords": [39.1000, -108.6900], "description": "Red rock canyons and monoliths along Rim Rock Drive — dogs at overlooks on leash", "type": "national_park"},
                ],
                "lodging": [
                    {"name": "Holiday Inn Express Gunnison", "type": "hotel", "dog_policy": "Dogs welcome with $25/night pet fee, mountain views", "price_range": "$100-150/night"},
                    {"name": "The Inn at Tomichi Village", "type": "hotel", "dog_policy": "Pet-friendly, $15/night fee, spacious rooms near downtown", "price_range": "$80-120/night"},
                    {"name": "Gunnison River Cabin (Airbnb)", "type": "airbnb", "dog_policy": "Dog-friendly cabin, fenced yard, near Blue Mesa Reservoir", "price_range": "$110-170/night"},
                ],
            },
            {
                "day": 5,
                "start": "Gunnison, CO",
                "end": "Parker, CO",
                "start_coords": [38.5458, -106.9253],
                "end_coords": [39.5186, -104.7614],
                "driving_hours": 4,
                "is_rest_day": False,
                "is_camping": False,
                "highlights": [
                    {"name": "Monarch Pass", "coords": [38.4972, -106.3258], "description": "11,312-foot mountain pass on US-50 with a scenic tram and Continental Divide views — quick stop for photos", "type": "scenic_drive"},
                    {"name": "Arkansas River Valley", "coords": [38.7300, -106.1400], "description": "Follow the Arkansas River through Salida and Buena Vista — dog-friendly river towns with mountain backdrops", "type": "scenic_drive"},
                ],
            },
        ],
    },
]

# Recalculate totals from daily values
for r in routes:
    r["total_driving_hours"] = sum(d["driving_hours"] for d in r["days"])

# Write the JSON file
output = {"routes": routes}
with open("data/route-proposals.json", "w") as f:
    json.dump(output, f, indent=2)

# Stats
for r in routes:
    highlights = sum(len(d.get("highlights", [])) for d in r["days"])
    hotel_nights = sum(1 for d in r["days"] if d.get("lodging"))
    camp_nights = sum(1 for d in r["days"] if d.get("camping"))
    print(f"Route {r['id']}: {r['name']} — {highlights} attractions, {hotel_nights} hotel nights, {camp_nights} camp nights, {r['total_driving_hours']}h driving")

total_highlights = sum(len(d.get("highlights", [])) for r in routes for d in r["days"])
print(f"\nTotal: {total_highlights} attractions across {len(routes)} routes")
